name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: SSH into Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          key: ${{ secrets.HOST_SSH_KEY }} # Use the private SSH key for the root user
          script: |
            cd /var/www/smart-supply-system-backendV1
            chmod +x deploy.sh
            ./deploy.sh $PAT

      - name: Timeout after 15 minutes
        run: echo "This job will timeout after 15 minutes"
