name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Overall job timeout

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH with ssh-agent
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.HOST_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-add id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: $SSH_AUTH_SOCK

      - name: Update deploy.sh on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_IP "echo '#!/bin/bash\n\necho \"Exit immediately if a command exits with a non-zero status.\"\nset -e\n\ngit pull https://$GITHUB_ACCESS_TOKEN@github.com/LD-Smart-Supply/smart-supply-system-backendV1.git\ndocker compose down\ndocker compose up -d --build' > /var/www/smart-supply-backendV1/deploy.sh"
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_USER: ${{ secrets.HOST_USER }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}

      - name: Execute Updated deploy.sh
        run: |
          ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_IP "chmod +x /var/www/smart-supply-backendV1/deploy.sh &&./var/www/smart-supply-backendV1/deploy.sh"
        env:
          HOST_IP: ${{ secrets.HOST_IP }}
          HOST_USER: ${{ secrets.HOST_USER }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
